
name: Share env vars across jobs

on:
  workflow_dispatch:

env:
  GITHUB_RUNNER: ubuntu
  GITHUB_RUNNER_VERSION: 22.04

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print ENV
        run: echo job1-${{ env.GITHUB_RUNNER }}-${{ env.GITHUB_RUNNER_VERSION }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print ENV
        run: echo job2-${{ env.GITHUB_RUNNER }}-${{ env.GITHUB_RUNNER_VERSION }}


